name: interactive_svg_widget
description: Flutter package to interact with different regions of an SVG.
version: 1.0.0
repository: https://github.com/HD16K/interactable_svg
issue_tracker: https://github.com/HD16K/interactable_svg/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics: 
  - svg
  - widget
  - flutter


environment:
  sdk: '>=2.14.4 <4.0.0'
  flutter: ">=2.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  svg_path_parser: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter



